// vim: ft=cpp
//
// Not intended for normal include. Use flags.h instead.
//
#ifndef C_FLAG_INCLUDE_TYPE_LAST
#define C_FLAG_INCLUDE_TYPE_LAST               C_FLAG_INCLUDE_TYPE
#define C_FLAG_INCLUDE_TYPE_LAST_DEFINED_LOCAL 1
#endif

// CFlagTypeIndex, type, postfix
C_FLAG_INCLUDE_TYPE( C_FLAG_INT, int, int )
C_FLAG_INCLUDE_TYPE( C_FLAG_INT_8, int8_t, int8 )
C_FLAG_INCLUDE_TYPE( C_FLAG_INT_16, int16_t, int16 )
C_FLAG_INCLUDE_TYPE( C_FLAG_INT_32, int32_t, int32 )
C_FLAG_INCLUDE_TYPE( C_FLAG_INT_64, int64_t, int64 )
C_FLAG_INCLUDE_TYPE( C_FLAG_UNSIGNED, unsigned, unsigned )
C_FLAG_INCLUDE_TYPE( C_FLAG_UINT_8, uint8_t, uint8 )
C_FLAG_INCLUDE_TYPE( C_FLAG_UINT_16, uint16_t, uint16 )
C_FLAG_INCLUDE_TYPE( C_FLAG_UINT_32, uint32_t, uint32 )
C_FLAG_INCLUDE_TYPE( C_FLAG_UINT_64, uint64_t, uint64 )
C_FLAG_INCLUDE_TYPE( C_FLAG_SIZE_T, size_t, size_t )
C_FLAG_INCLUDE_TYPE( C_FLAG_BOOL, bool, bool )
C_FLAG_INCLUDE_TYPE( C_FLAG_STRING, char *, string )
C_FLAG_INCLUDE_TYPE( C_FLAG_FLOAT, float, float )
C_FLAG_INCLUDE_TYPE_LAST( C_FLAG_DOUBLE, double, double )

#ifdef C_FLAG_INCLUDE_TYPE_LAST_DEFINED_LOCAL
#undef C_FLAG_INCLUDE_TYPE_LAST_DEFINED_LOCAL
#undef C_FLAG_INCLUDE_TYPE_LAST
#endif
