name: 'xiejw-action'
description: 'Common Action'
inputs:
  repo_at:
    default: y
  compile_eva:
    default: false
  compile_eve:
    default: false
  require_clang:
    default: false
  clang_version:
    default: 15
  require_gcc:
    default: false
  gcc_version:
    default: 12
  require_go:
    default: false
  go_version:
    default: 1.23
runs:
  using: "composite"
  steps:

    # --------------------------------------------------------------------------
    # Clang related
    #
    # https://brandur.org/fragments/github-actions-env-vars-in-env-vars
    - name: Set environmental variables for Clang
      if: ${{ inputs.require_clang == 'true' }}
      shell: bash
      run: |
        echo "CC=clang-${{ inputs.clang_version }}" >> $GITHUB_ENV
        echo "CXX=clang++-${{ inputs.clang_version }}" >> $GITHUB_ENV
    - name: Install LLVM and Clang
      if: ${{ inputs.require_clang == 'true' }}
      shell: bash
      run: |
        sudo apt-get install -y --no-install-recommends \
            clang-${{ inputs.clang_version }}           \
            lld-${{ inputs.clang_version }}             \
            libclang-${{ inputs.clang_version }}-dev    \
            libclang-rt-${{ inputs.clang_version}}-dev
    - name: Display Clang version
      if: ${{ inputs.require_clang == 'true' }}
      shell: bash
      run: ${CC} --version

    # --------------------------------------------------------------------------
    # GCC related
    #
    - name: Set environmental variables for GCC
      if: ${{ inputs.require_gcc == 'true' }}
      shell: bash
      run: |
        echo "CC=gcc-${{ inputs.gcc_version }}" >> $GITHUB_ENV
        echo "CXX=g++-${{ inputs.gcc_version }}" >> $GITHUB_ENV
    - name: Install GCC
      if: ${{ inputs.require_gcc == 'true' }}
      shell: bash
      run: sudo apt-get install -y --no-install-recommends g++-${{ inputs.gcc_version }}
    - name: Display GCC version
      if: ${{ inputs.require_gcc == 'true' }}
      shell: bash
      run: ${CC} --version

    # --------------------------------------------------------------------------
    # Eva related
    #
    - name: Prepare Eva
      if: ${{ inputs.compile_eva == 'true' }}
      shell: bash
      run: |
        echo "NO_CLANG_FLAGS=1" >> $GITHUB_ENV
    - name: Build Eva
      if: ${{ inputs.compile_eva == 'true' }}
      shell: bash
      run: |
        make -C ${{ github.workspace }}/${{ inputs.repo_at }}/ann/eva release

    # --------------------------------------------------------------------------
    # Eve related
    #
    - name: Build Eve
      if: ${{ inputs.compile_eve == 'true' }}
      shell: bash
      run: |
        make -C ${{ github.workspace }}/${{ inputs.repo_at }}/ann/eve release

    # --------------------------------------------------------------------------
    # Go related
    #
    - name: Set environmental variables for Go
      if: ${{ inputs.require_go == 'true' }}
      shell: bash
      run: |
        echo "GO=/usr/lib/go-${{ inputs.go_version }}/bin/go" >> $GITHUB_ENV
    - name: Install Go
      if: ${{ inputs.require_go == 'true' }}
      shell: bash
      run: sudo apt-get install -y --no-install-recommends golang-${{ inputs.go_version }}
    - name: Display Go version
      if: ${{ inputs.require_go == 'true' }}
      shell: bash
      run: ${GO} version

