name: 'xiejw-action'
description: 'Common Action'
inputs:
  repo_at:
    default: y
  compile_eva:
    default: false
  require_clang:
    default: false
  clang_version:
    default: 15
  require_go:
    default: false
  go_version:
    default: 1.21
runs:
  using: "composite"
  steps:

    # --------------------------------------------------------------------------
    # Clang related
    #
    # https://brandur.org/fragments/github-actions-env-vars-in-env-vars
    - name: Set environmental variables for Clang
      if: ${{ inputs.require_clang == 'true' }}
      shell: bash
      run: |
        echo "CC=clang-${{ inputs.clang_version }}" >> $GITHUB_ENV
        echo "CXX=clang++-${{ inputs.clang_version }}" >> $GITHUB_ENV
    - name: Install LLVM and Clang
      if: ${{ inputs.require_clang == 'true' }}
      shell: bash
      run: sudo apt-get install -y --no-install-recommends clang-${{ inputs.clang_version }}
    - name: Display Clang version
      if: ${{ inputs.require_clang == 'true' }}
      shell: bash
      run: ${CC} --version

    # --------------------------------------------------------------------------
    # Eva related
    #
    - name: Prepare Eva
      if: ${{ inputs.compile_eva == 'true' }}
      shell: bash
      run: |
        echo "NO_CLANG_FLAGS=1" >> $GITHUB_ENV
    - name: Build Eva
      if: ${{ inputs.compile_eva == 'true' }}
      shell: bash
      run: |
        make -C ${{ github.workspace }}/${{ inputs.repo_at }}/ann/eva release

    # --------------------------------------------------------------------------
    # Go related
    #
    - name: Set environmental variables for Go
      if: ${{ inputs.require_go == 'true' }}
      shell: bash
      run: |
        echo "GO=/usr/lib/go-${{ inputs.go_version }}/bin/go" >> $GITHUB_ENV
    - name: Install Go
      if: ${{ inputs.require_go == 'true' }}
      shell: bash
      run: sudo apt-get install -y --no-install-recommends golang-${{ inputs.go_version }}
    - name: Display Go version
      if: ${{ inputs.require_go == 'true' }}
      shell: bash
      run: ${GO} version

