# vim: nofoldenable

unbind C-b
set -g prefix C-o
bind-key C-o send-prefix

bind r source-file ~/.tmux.conf \; display "Load Config."

# {{{1 Colors and Styles.
# {{{2 Colors.
set -g default-terminal "screen-256color"

# {{{2 Inactive/Active Window Colors and Styles
set -g pane-border-style bg=colour235,fg=colour238
set -g pane-active-border-style bg=colour236,fg=colour51

# 2022-06 unset the window style so tmux will not disable terminal's opacity
# set -g window-active-style 'bg=colour235'
# set -g window-style 'bg=colour237'

# {{{1 Basic Windows, Panes and Status Configuration.
# {{{2 Index. Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-option -g history-limit 5000

# {{{2 Status Related.
set-option -g status-position top
set-option -g window-status-current-style fg=colour235,bg=white

# {{{1 Copy-Mode.
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

# === --- Panes ------------------------------------------------------------ ===

# === --- Pane Splitting
bind-key v split-window -h -p 33  # one third on right.
bind-key s split-window -v

# === --- Resize pane (Repeatedly)
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r H resize-pane -L 5
bind-key -r L resize-pane -R 5

# === --- Pane Selection (Vim style)
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# === --- Pane Selection (without prefix) M - Option
#
# On macOs, this might not work well. Need to config termimal to send these
# keys to tmux. See more in ~/.config/kitty/kitty.conf
#
bind-key -n M-h select-pane -L
bind-key -n M-j select-pane -D
bind-key -n M-k select-pane -U
bind-key -n M-l select-pane -R
# Next pane
bind-key -n M-f select-pane -t :.+

# {{{1 Others.

# {{{3 Reduce ESC delay for vim.
set -sg escape-time 0

# === --- Mouse related ---------------------------------------------------- ===
#
# Enable mouse and when the mouse is scolled up, enable copy mode directly.
set -g mouse on

bind -n WheelUpPane if-shell -F -t = "#{pane_in_mode}" \
  "send-keys -M" \
  "copy-mode -e; send-keys -M"

bind -n WheelDownPane select-pane -t= \; send-keys -M

