# vim: nofoldenable

# === --- Global Configurations -------------------------------------------- ===

# === --- Rebind C-o as prefix. C-b is hard for left hand.
#
unbind C-b
set -g prefix C-o
bind-key C-o send-prefix

# === --- Enable mouse
set -g mouse on

# === --- Reduce ESC delay for vim.
set -sg escape-time 0

# === --- Basic window, pane configuration.
#
# Adjust all index (window, pane) staring at 1, not 0
set -g base-index 1
set -g pane-base-index 1

# Make history longer.
set -g history-limit 5000

# Put Status bar to top.
set -g status-position top

# === --- Colors ----------------------------------------------------------- ===
#
# Enable 256 colors
set -g default-terminal "screen-256color"

# Adjust status bar.
set -g window-status-current-style fg=colour235,bg=white

# Adjust inactive/Active Window Colors and Styles
set -g pane-border-style bg=colour235,fg=colour238
set -g pane-active-border-style bg=colour236,fg=colour51

# Make active pane more obvious
set -g window-active-style 'bg=colour235'
set -g window-style 'bg=colour237'

# === --- Panes ------------------------------------------------------------ ===

# === --- Pane Splitting
bind-key v split-window -h -p 33  # one third on right.
bind-key s split-window -v

# === --- Resize pane (Repeatedly)
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r H resize-pane -L 5
bind-key -r L resize-pane -R 5

# === --- Pane Selection (Vim style)
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# === --- Pane Selection (without prefix) M - Option
#
# On macOs, this might not work well. Need to config termimal to send these
# keys to tmux. See more in ~/.config/kitty/kitty.conf
#
bind-key -n M-h select-pane -L
bind-key -n M-j select-pane -D
bind-key -n M-k select-pane -U
bind-key -n M-l select-pane -R
# Select next pane super fast
bind-key -n M-f select-pane -t :.+

# === --- Copy-Mode -------------------------------------------------------- ===
#
# === --- Make select and copy in copy mode like vim
#
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

# === --- Enable copy mode when scrolled up by mouse.
#
# NOTE: This is very helpful to review plans generated by Claude.

bind-key -n WheelUpPane if-shell -F -t = "#{pane_in_mode}" \
  "send-keys -M" \
  "copy-mode -e; send-keys -M"

bind-key -n WheelDownPane select-pane -t= \; send-keys -M

