name: eva
run-name: ${{ github.actor }} is running tests for ${{ github.workflow }}
on: [push]
env:
  CLANG_VERSION: 15
  NO_CLANG_FLAGS: 1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install LLVM and Clang
        run: sudo apt-get install -y clang-$CLANG_VERSION
      - name: Set environmental variables
        run: |
          echo "CC=clang-$CLANG_VERSION" >> $GITHUB_ENV
          echo "CXX=clang++-$CLANG_VERSION" >> $GITHUB_ENV
      - name: Display Clang version
        run: ${CC} --version
      - name: Run ${{ github.workflow }} Test
        env:
        run: make -C ${{ github.workspace }}/ann/${{ github.workflow }} clean test
      - name: Run ${{ github.workflow }} Release
        env:
        run: make -C ${{ github.workspace }}/ann/${{ github.workflow }} release

