name: eva
run-name: ${{ github.actor }} is running tests for ${{ github.workflow }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: y
      - uses: ./y/.github/actions/base
        with:
          compile_eva: true  # This will run release
          require_clang: true
      - name: Run ${{ github.workflow }} Test
        run: make -C ${{ github.workspace }}/ann/${{ github.workflow }} clean test

