run-name: ${{ github.actor }} is running tests for ${{ github.workflow }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          path: y
      - uses: ./y/.github/actions/base
        with:
          require_gcc: true
          require_go: true
      - name: Install fd
        shell: bash
        run: |
          sudo apt-get install -y --no-install-recommends \
              fd-find
      - name: Create fd alias
        run: sudo ln -s $(which fdfind) /usr/local/bin/fd && fd --version
      - name: Run ${{ github.workflow }} Test
        run: make -C ${{ github.workspace }}/y/ clean test
